export const ON_CHANGE = 'ON_CHANGE';

export const EDIT_DISH = 'EDIT_DISH';

export const DISHES_REQUEST= 'DISHES_REQUEST';
export const DISHES_SUCCESS = 'DISHES_SUCCESS';

export const ORDERS_REQUEST = 'ORDERS_REQUEST';
export const ORDERS_SUCCESS = 'ORDERS_SUCCESS';
